Vue/signin
mvvkinn/interview-system pull request #18
Opened 2022-11-21 06:58 UTC by taemin-jang

Add login check and the ability to store user information on local storage.
Add login token save function using Vue-cookies package.
Add email duplicate checking to signup page.
Add DaumPostcode API.

로그인 검사 및 로컬 저장소에 사용자 정보를 저장하는 기능을 추가합니다.
Vue-cookies 패키지를 사용하여 로그인 토큰 저장 기능 추가합니다.
회원가입 페이지에 이메일 중복 검사를 추가합니다.
다음 우편 번호 API를 추가합니다.

2022-11-22 09:50 UTC, LSeolAh approved these changes

2022-11-22 11:56 UTC, mvvkinn commented on vue/package.json
> +    "vuex": "3.6.2"
이전엔 4.1.0 버전을 쓰다가 구버전으로 다운그레이드 한 이유가 있을까요?

2022-11-22 12:00 UTC, mvvkinn commented on vue/src/store/index.js
> +          commit("isLogin", true);
어떤 기능을 하는지 궁금합니다.

2022-11-22 12:26 UTC, mvvkinn requested changes

2022-11-22 12:26 UTC, mvvkinn commented on vue/src/views/joinus/SignUp.vue
> +        email: this.email === "" ? this.email : this.email + "@" + this.domain,
이메일 도메인을 직접 입력하면 데이터베이스에 도메인이 입력되지 않습니다. 확인해주세요

2022-11-22 13:25 UTC, taemin-jang commented on vue/src/store/index.js
> +          commit("isLogin", true);
로그인 페이지에서 api 통신 후 로그인 성공 유무 값을 전달해줍니다.
그런데 실패 했을 때 false로 전달하는 것이 의미가 명확할 것 같네요. 수정하겠습니다

2022-11-22 13:26 UTC, mvvkinn commented on vue/src/store/index.js
> +          commit("isLogin", true);
따로 에러 핸들링은 안하는건가요?

2022-11-22 16:11 UTC, taemin-jang commented on vue/src/store/index.js
> +          commit("isLogin", true);
에러 핸들링 반영했습니다

2022-11-22 16:11 UTC, taemin-jang commented on vue/src/views/joinus/SignUp.vue
> +        email: this.email === "" ? this.email : this.email + "@" + this.domain,
수정했습니다

2022-11-23 12:20 UTC, mvvkinn requested changes

2022-11-23 12:20 UTC, mvvkinn commented on vue/src/views/joinus/SignUp.vue
> +        email: this.email === "" ? this.email : this.email + "@" + this.domain,
이번엔 중복 이메일 입력하면 도메인 부분이 아에 지워져 버리는데 확인 다시한번 해주세요

2022-11-23 12:20 UTC, mvvkinn commented on vue/src/views/joinus/SignUp.vue
>    },
우편번호 클릭했을때 창이 열리지 않아요 확인해주세요.

2022-11-24 07:05 UTC, merged

2022-11-24 07:05 UTC, mvvkinn approved these changes
특정 디바이스 chromium 계열 브라우저에서 카카오 API 로드 안되는 문제를 issue 생성하고 해당 브랜치는 merge 하도록 함